---
- name: Block IP Address
  hosts: checkpoint
  become: true
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present

    - name: Creating a new firewall rule
      ufw:
        rule: deny
        from: 192.168.56.128

    - name: Restart UFW Firewall
      service:
        name: ufw
        state: restarted
        enabled: yes
